# Generated by Django 4.2.3 on 2023-07-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='frase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField(verbose_name='Texto')),
                ('like', models.IntegerField(verbose_name='Like')),
                ('idLink', models.IntegerField(verbose_name='LINK')),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(verbose_name='URL')),
                ('clase', models.TextField(verbose_name='Class')),
                ('tipo', models.TextField(verbose_name='tipo')),
                ('detalle', models.CharField(max_length=50, verbose_name='Detalle')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
    ]
