# Generated by Django 4.2.3 on 2023-07-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frase',
            name='idLink',
        ),
        migrations.RemoveField(
            model_name='frase',
            name='like',
        ),
        migrations.RemoveField(
            model_name='frase',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='link',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='link',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='link',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='link',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='link',
            name='url',
        ),
        migrations.AlterField(
            model_name='frase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='frase',
            table='frase',
        ),
        migrations.AlterModelTable(
            name='link',
            table='link',
        ),
    ]
