# Generated by Django 4.2.3 on 2023-07-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_remove_frase_idlink_remove_frase_like_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frase',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'managed': False},
        ),
    ]
