# Generated by Django 4.2.3 on 2023-07-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_frase_options_alter_link_options'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='frase',
            table_comment='\t',
        ),
    ]
