# Generated by Django 4.2.3 on 2023-07-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_alter_frase_table_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={},
        ),
    ]
