# Generated by Django 4.2.3 on 2023-07-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_alter_frase_options_alter_link_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frase',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'managed': False},
        ),
    ]
