# Generated by Django 4.2.3 on 2023-07-21 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_remove_link_detalleid_delete_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='frase',
            name='idlink',
            field=models.ForeignKey(db_column='idlink', on_delete=django.db.models.deletion.DO_NOTHING, to='libreria.link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=45),
        ),
        migrations.AlterField(
            model_name='link',
            name='tipoid',
            field=models.ForeignKey(db_column='tipoid', on_delete=django.db.models.deletion.DO_NOTHING, to='libreria.tipo'),
        ),
    ]
